import Link from 'next/link'
import './globals.css'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="p-4 bg-pokemon-red">
        <div className="mx-auto max-w-[50vh] max-h-[25vh] w-full">

        </div>
        <main className="mx-auto aspect-square max-h-[50vh] overflow-y-auto overflow-x-hidden border-solid border-[40px] border-pokemon-almond rounded-md rounded-bl-[30px] bg-slate-50 p-2">
          {children}
        </main>
        <nav className="mx-auto max-w-[50vh] max-h-[25vh] w-full flex gap-4">
          <div className="rounded-full h-16 w-16 bg-slate-700 mt-8">
            <Link className="w-full h-full block" href="/"><span className="sr-only">Home</span></Link>
          </div>
        </nav>
      </body>
    </html>
  )
}
